# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

baseURL         = "https://reuse.software/"
languageCode    = "en"
title           = "REUSE"
theme           = "github-project-landing-page"
sectionPagesMenu = "main"

#[permalinks]
#        page = "/:title/"
#        about = "/:filename/"


[params]
    subtitle = "Make licensing easy for everyone"
    description = "We make licensing easy for humans and machines alike. REUSE solves a fundamental issue that Free Software licensing has at the very source. Adopting our recommendations is as easy as one-two-three!"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

[params.social]
  Github        = "search?q=topic%3Areuse+org%3Afsfe&type=Repositories"
  Git           = "https://git.fsfe.org/reuse"
  Email         = "https://lists.fsfe.org/mailman/listinfo/reuse"
  Twitter       = "fsfe"
  Stackoverflow = ""
  Mastodon      = "mastodon.social/@fsfe"
  Diaspora      = ""

[menu]
[[menu.main]]
  name = "Get Started"
  identifier = "tutorial"
  weight = 100
  url = "/tutorial/"
[[menu.main]]
  name = "FAQ"
  identifier = "faq"
  weight = 200
  url = "/faq/"
[[menu.main]]
  name = "Developers"
  identifier = "dev"
  weight = 300
  url = "/dev/"
[[menu.main]]
  name = "Specification"
  identifier = "spec"
  weight = 300
  url = "/spec/"
[[menu.main]]
  name = "Materials"
  identifier = "materials"
  weight = 900
  url = "/materials/"
[[menu.main]]
  name = "API"
  identifier = "api"
  weight = 1000
  url = "https://api.reuse.software"
